- uses: actions/setup-node@v4
  with: { node-version: 20 }
- run: corepack enable
- uses: pnpm/action-setup@v3
  with: { version: 9, run_install: true }
- run: pnpm build
- run: pnpm -s test || echo 'no tests'
