name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Check Python syntax
        run: python -m py_compile engine/*.py
      
      - name: Verify imports
        run: python -c "from engine import engine_server, task_api, task_runner, engine_daemon"
      
      - name: Test Docker build
        run: docker build -t openwebui-engine:test .
